### ISSUE TITLE
Source microflow is not triggered

### ISSUE THREAD

**Issue by David-Sanders** [Criccle/GoogleGantt#1]
I am having an issue where the chart is sometimes rendered once, but afterwards it does not render at all.  Placing a debug action in the source microflow shows that the microflow is not being called when the page containing the gantt chart is opened.

This is the debug info in the browser:

.constructor
mxui.js...1201933 (line 29)
GoogleGantt_widget_GoogleGantt_0.postCreate
mxui.js...1201933 (line 29)
GoogleGantt_widget_GoogleGantt_0._updateRendering
mxui.js...1201933 (line 29)
GoogleGantt_widget_GoogleGantt_0.update
mxui.js...1201933 (line 29)
GoogleGantt_widget_GoogleGantt_0._resetSubscriptions
mxui.js...1201933 (line 29)
GoogleGantt_widget_GoogleGantt_0._updateRendering
mxui.js...1201933 (line 29)
HelpText_widget_HelpTextAttr_0.uninitialize
mxui.js...1201933 (line 29)
GoogleGantt_widget_GoogleGantt_0.resize

**Comment by Criccle** [comment]
Hi David, thanks for reporting this issue and providing the debug info. It looks as though the updateRendering function is the problem. Once finished, this should call getData and other functions (which you'll probably see in the debug info when the chart does render).

What browser do you use? I will look into the issue next week.

**Comment by David-Sanders** [comment]
Hi Willem

I am using Firefox as my main browser, but have tested in Chrome and IE and get the same issue

Thanks for looking in to it

Regards… Dave

David Sanders

Solution Architect

e-ServiceSuite 

tel +44 1494 468980

mobile +44 7710 377761

email david.sanders@westoverconsulting.co.uk

web   http://www.e-servicesuite.co.uk http://www.e-servicesuite.co.uk/ 

certification-rapid

**Comment by David-Sanders** [comment]
Hi Willem

I downloaded your latest version from GitHub and the height issue seems to be resolved – well done.  Is there any progress on getting the widget to render consistently?

Regards… Dave

David Sanders

Solution Architect

e-ServiceSuite 

tel +44 1494 468980

mobile +44 7710 377761

email david.sanders@westoverconsulting.co.uk

web   http://www.e-servicesuite.co.uk http://www.e-servicesuite.co.uk/ 

certification-rapid

**Comment by Criccle** [comment]
Hi David,

I sent you an email on June 27th from my work email address with the newest
widget included (same as is now on Github). I was hoping the render issue
would be fixed in this version. But I also added a description that I put
more logging into the widget, in the hope that you could test it again and
tell me which logging you receive now. This should pinpoint us to what is
actually going wrong.

Hope to hear from you soon, so we can fix this issue ASAP! :-)

**Comment by David-Sanders** [comment]
Hi Willem

I was away last week and must have missed that email…

It looks to me that when the chart does not render, it is failing at this line 289:

```
                        if(!window._googleVisualization || window._googleVisualization === false) {
```

(I added an else action to this to log if it failed)

Regards… Dave

**Comment by Criccle** [comment]
Yeah you're right. That's the reason why I added some extra logging to
determine what exactly is missing etcetera. I have resent the email. Would
you be willing to test it and send me the logging?
