### ISSUE TITLE
Height of gantt chart created

### ISSUE THREAD

**Issue by David-Sanders** [Criccle/GoogleGantt#2]
The height of the chart seems to be hard coded to 275.  This truncates the size of the chart if there are more than about 7 tasks in the list. Would it be better to have the height calculated on the number of rows in the data array, something like height: (returnedList.length \* 40), (from the _createTable function)

This would require that vertical scrollbars be enabled for large charts

**Comment by Criccle** [comment]
You're absolutely right. Guess I overlooked the height, woops! In the next version I'll remove the height from the options, then the chart should use the height of the containing element.

Thanks for reporting the issue!

**Comment by Criccle** [comment]
Hi David, it turns out the height was not automatically set by removing it from the options. I implemented your solution and that works perfectly. It will be included in the next release. Before releasing a new version I will try and solve your other issue as well.
