### ISSUE TITLE
Chart trimmed by an invisible svg area, which limits the graph to 6 visible tasks/rows.

### ISSUE THREAD

**Issue by patricos** [Criccle/GoogleGantt#3]
Hi, I'm experiencing a repetive, universally reproducible issue with the size (i.e. height) of the box surrounding the Gantt graph.  Sending above 6 tasks to the entity that stores graph's rows results in: trimming 7th task, and all other tasks being not visible, and x-axis being not visible.
## VERSIONS:
- Mendix Modeller 6.6.0.
- All (three major) browsers we tried.
- All currently available Widget versions (1.0 and 2.0).
## PROBLEM DESCRIPTION:

The graph is rendered at the page within an svg region, whose height seems to be hard-coded in Mendix widget.  In the website object-inspector it reads : '<svg height="275" ', where height=275 is there regardless of the size of the surrounding object.
## REPRODUCIBILITY:

How to re-create: just try to display 20 tasks at Gantt graph.  According to our experience, 7th, 8th, 9th... all will be invisible.

The problem does not depend on the layout chosen in Modeler, AND can be observed also in the example app (downloaded from github), AND is independent from the browser (we tried FF, Chrome, IE)
## MORE INFO:

It is possible to alter the height parameter manually: in the object inspector in the browser, and this can lead to setting a propoer value that entangles the graph precisely (but only in the run-time).  The graph-side logics is correct, because the graph contains all tasks;  just the display part is incorrect, becouse it trims the graph.

I am very much looking forward to hearing from developers.  Please help!

Kind regards,
Patryk Mazurkiewicz

**Comment by Criccle** [comment]
Hi Patryk! Thanks for reporting the issue and providing so much information. I received a similar issue a week and a half ago and came to the conclusion that I set the height fixed to 275 pixels (woops!). The next version will have a correct height set, depending on the amount of tasks. 

I was hoping to get some feedback on another issue soon, so I could fix all of them and update the widget in the App Store. Since you're the second person to report this issue I'll submit a new version (with a fix for this issue!) to the App Store tomorrow.

Thanks again!

Kind regards,
Willem van Zantvoort

**Comment by patricos** [comment]
Hi Willem!  Thank you for your enlightening response and also for the speed-of-light reaction.

This conversation has helped me to repair the height of the graph, however, I think that the line 210 of GoogleGantt.js should read: "this._height = (returnedList.length + 1) \* 40;" instead of just "this._height = returnedList.length \* 40;".  This is because the x-axis also takes up some space.

I have repaired that in my application myself.  I am now looking forward to the results of your hard work on the problem with updateRendering function, as I also observe the problem described by David Sanders in the issue #1 .

Thank you for your great work you do for the community on this widget!

Kind regards,
Patryk Mazurkiewicz
