### ISSUE TITLE
Stopped working in Mendix 7.16.0

### ISSUE THREAD

**Issue by David-Sanders** [Criccle/GoogleGantt#4]
Get error unable to create widget when running in Mx7.16.0

**Comment by JelteMX** [comment]
Check [this version](https://github.com/Criccle/GoogleGantt/raw/master/dist/GoogleGantt.mpk) that was merged today. That should fix the issue, because we've seen the same behavior.

**Comment by David-Sanders** [comment]
Many thanks - that solved the issue
